version: '3.1'

services:
  db:
    image: mysql:5.7.26
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_HOSTNAME: 0.0.0.0
      MYSQL_DATABASE: db_example
      MYSQL_USER: springuser
      MYSQL_PASSWORD: ThePassword
    ports:
      - 3306:3306

  app:
    build: .
    command: mvn exec:java
    depends_on:
      - db
    ports:
      - 8080:8080